### ISSUE TITLE
Error in SCORE2013

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ikarosilva/wfdb-app-toolbox#14]
```
 I am trying to use the Matlab score2013 function on a Windows XP
>
> Error: Cannot convert to double:
>
> init: can't open header for record a01
>
> Could not score event 2 on entry: fqrs_entry1
>
> java.lang.NumberFormatException: Cannot convert
>
>                 at
org.physionet.wfdb.Wfdbexec.execToDoubleArray(Unknown
> Source)
>
>                 at org.physionet.wfdb.Score2013.score1(Unknown Source)
>
>                 at org.physionet.wfdb.Score2013.getScore(Unknown
Source)
>
> ??? Error using ==> score2013 at 115
>
> Java exception occurred:
>
> java.lang.NullPointerException
>
>
>
>                 at org.physionet.wfdb.Score2013.score1(Unknown Source)
>
>
>
>                 at org.physionet.wfdb.Score2013.getScore(Unknown
Source)


```

Original issue reported on code.google.com by `ikarosil...@gmail.com` on 15 Jan 2014 at 6:43

**Comment by paryatavoosi** [comment]
I could not run score2013.m in MATLAB 2014a in my MAC with Yosemite. I got the 
following error.
Error: Cannot convert to double: 
init: can't open header for record C:\Program Files\MATLAB\R2016b\project\tavoosi\data\set-a\a01
Error using tach (line 84)
Java exception occurred:
java.lang.NumberFormatException: Cannot convert

	at org.physionet.wfdb.Wfdbexec.execToDoubleArray(Unknown Source)
